routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| MAIN
|--------------------------------------------------------------------------
*/

Route::get('/', 'Controller@home')->name('home');
Route::get('/club/presentation', 'Controller@presentation')->name('club.presentation');
Route::get('/club/equipe', 'Controller@equipe')->name('club.equipe');
Route::get('/horaires-tarifs/horaires', 'Controller@horaires')->name('horaires-tarifs.horaires');
Route::get('/horaires-tarifs/tarifs', 'Controller@tarifs')->name('horaires-tarifs.tarifs');
Route::get('/competitions/calendrier', 'Controller@calendrier')->name('competitions.calendrier');
Route::get('/competitions/resultats', 'Controller@resultats')->name('competitions.resultats');
Route::get('/galerie', 'Controller@galerie')->name('galerie');
Route::get('/galerie/{galerie}', 'Controller@galerieDetails')->name('galerieDetails');


/*
|--------------------------------------------------------------------------
| INTRANET
|--------------------------------------------------------------------------
*/

Auth::routes();

Route::prefix('intranet')->middleware('role:superadministrator|administrator|moderator|secretary|trainer|accountant|contributor|guest')->group(function(){
    Route::get('/', 'IntraController@index')->name('intranet');
    Route::get('dashboard', 'IntraController@dashboard')->name('intranet.dashboard');

    Route::get('/profil', 'ProfileController@showProfile')->name('showProfile');
    Route::get('/profil/edit','ProfileController@showChangePasswordForm')->name('editProfile');
    Route::post('/profil/edit','ProfileController@changePassword')->name('updateProfile');

    Route::get('/actualites/{actualite}/delete', 'ActualiteController@delete')->name('actualites.delete');

    Route::get('/judokas/{judoka}/unarchive', 'JudokaController@unarchive')->name('judokas.unarchive');
    Route::get('/judokas/{judoka}/pdf', 'JudokaController@pdf')->name('judokas.pdf');
    Route::resource('/judokas', 'JudokaController');

    Route::resource('/actualites', 'ActualiteController');
    Route::resource('/calendrier', 'CalendrierController');
    Route::resource('/resultats', 'ResultatController');
    Route::resource('/galerie', 'GalerieController');
    Route::resource('/fiches-de-frais', 'FraisController');

    Route::resource('/users', 'UserController');
    Route::resource('/permissions', 'PermissionController');
    Route::resource('/roles', 'RoleController');

    Route::get('/actualites/{actualite}/accept', 'ActualiteController@accept')->name('actualites.accept');
    Route::get('/actualites/{actualite}/reject', 'ActualiteController@reject')->name('actualites.reject');
    Route::get('/calendrier/{calendrier}/accept', 'CalendrierController@accept')->name('calendrier.accept');
    Route::get('/calendrier/{calendrier}/reject', 'CalendrierController@reject')->name('calendrier.reject');
});

app/Permission.php
<?php

namespace App;

use Laratrust\Models\LaratrustPermission;

class Permission extends LaratrustPermission
{
    //
}

app/Http/Controllers/PermissionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Permission;
use Session;

class PermissionController extends Controller
{
  public function __construct()
    {
        $this->middleware('role:superadministrator');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $permissions = Permission::all();
      return view('intranet.permissions.index')->withPermissions($permissions);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      return view('intranet.permissions.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
      if ($request->permission_type == 'basic') {
        $this->validateWith([
          'display_name' => 'required|max:255',
          'name' => 'required|max:255|alphadash|unique:permissions,name',
          'description' => 'sometimes|max:255'
        ]);
        $permission = new Permission();
        $permission->name = $request->name;
        $permission->display_name = $request->display_name;
        $permission->description = $request->description;
        $permission->save();
        return redirect()->route('permissions.index');
      } elseif ($request->permission_type == 'crud') {
        $this->validateWith([
          'resource' => 'required|min:3|max:100|alpha'
        ]);
        $crud = explode(',', $request->crud_selected);
        if (count($crud) > 0) {
          foreach ($crud as $x) {
            $slug = strtolower($x) . '-' . strtolower($request->resource);
            $display_name = ucwords($x . " " . $request->resource);
            $description = "Allows a user to " . strtoupper($x) . ' a ' . ucwords($request->resource);
            $permission = new Permission();
            $permission->name = $slug;
            $permission->display_name = $display_name;
            $permission->description = $description;
            $permission->save();
          }
          return redirect()->route('permissions.index');
        }
      } else {
        return redirect()->route('permissions.create')->withInput();
      }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $permission = Permission::findOrFail($id);
      return view('intranet.permissions.show')->withPermission($permission);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $permission = Permission::findOrFail($id);
      return view('intranet.permissions.edit')->withPermission($permission);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
      $this->validateWith([
        'display_name' => 'required|max:255',
        'description' => 'sometimes|max:255'
      ]);
      $permission = Permission::findOrFail($id);
      $permission->display_name = $request->display_name;
      $permission->description = $request->description;
      $permission->save();
      return redirect()->route('permissions.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/intranet/permissions/create.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')

<div class="flex-container">
  <div class="columns m-t-10">
    <div class="column">
      <h1 class="title">
        <a href="{{route('permissions.index')}}" class="button is-outlined m-r-10">
          <span class="icon">
            <i class="fas fa-chevron-left"></i>
          </span>
        </a>Nouvelle permission</h1>
    </div>
  </div>
  <hr class="m-t-0">

  <div class="columns">
    <div class="column">
      <form action="{{route('permissions.store')}}" method="POST">
        {{csrf_field()}}

        <div class="block">
          <b-radio v-model="permissionType" name="permission_type" native-value="basic">Basic Permission</b-radio>
          <b-radio v-model="permissionType" name="permission_type" native-value="crud">CRUD Permission</b-radio>
        </div>

        <div class="field" v-if="permissionType == 'basic'">
          <label for="display_name" class="label">Name (Display Name)</label>
          <p class="control">
            <input type="text" class="input" name="display_name" id="display_name">
          </p>
        </div>

        <div class="field" v-if="permissionType == 'basic'">
          <label for="name" class="label">Slug</label>
          <p class="control">
            <input type="text" class="input" name="name" id="name">
          </p>
        </div>

        <div class="field" v-if="permissionType == 'basic'">
          <label for="description" class="label">Description</label>
          <p class="control">
            <input type="text" class="input" name="description" id="description" placeholder="Describe what this permission does">
          </p>
        </div>

        <div class="field" v-if="permissionType == 'crud'">
          <label for="resource" class="label">Resource</label>
          <p class="control">
            <input type="text" class="input" name="resource" id="resource" v-model="resource" placeholder="The name of the resource">
          </p>
        </div>

        <div class="columns" v-if="permissionType == 'crud'">
          <div class="column is-one-quarter">
            <div class="field">
              <b-checkbox v-model="crudSelected" native-value="create">Create</b-checkbox>
            </div>
            <div class="field">
              <b-checkbox v-model="crudSelected" v-model="crudSelected" native-value="read">Read</b-checkbox>
            </div>
            <div class="field">
              <b-checkbox v-model="crudSelected" native-value="update">Update</b-checkbox>
            </div>
            <div class="field">
              <b-checkbox v-model="crudSelected" native-value="delete">Delete</b-checkbox>
            </div>
          </div>
          <!-- end of .column -->

          <input type="hidden" name="crud_selected" :value="crudSelected">

          <div class="column">
            <table class="table" v-if="resource.length >= 3 && crudSelected.length > 0">
              <thead>
                <th>Name</th>
                <th>Slug</th>
                <th>Description</th>
              </thead>
              <tbody>
                <tr v-for="item in crudSelected">
                  <td v-text="crudName(item)"></td>
                  <td v-text="crudSlug(item)"></td>
                  <td v-text="crudDescription(item)"></td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <button class="button is-success">Create Permission</button>
      </form>
    </div>
  </div>

</div>
<!-- end of .flex-container -->
@endsection
 
@section('scripts')
<script>
  var app = new Vue({
      el: '#app',
      data: {
        permissionType: 'basic',
        resource: '',
        crudSelected: ['create', 'read', 'update', 'delete']
      },
      methods: {
        crudName: function(item) {
          return item.substr(0,1).toUpperCase() + item.substr(1) + " " + app.resource.substr(0,1).toUpperCase() + app.resource.substr(1);
        },
        crudSlug: function(item) {
          return item.toLowerCase() + "-" + app.resource.toLowerCase();
        },
        crudDescription: function(item) {
          return "Autoriser un utilisateur à " + item.toUpperCase() + " un " + app.resource.substr(0,1).toUpperCase() + app.resource.substr(1);
        }
      }
    });

</script>
@endsection

resources/views/intranet/permissions/edit.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')
<div class="flex-container">
  <div class="columns m-t-10">
    <div class="column">
      <h1 class="title">
        <a href="{{route('permissions.index')}}" class="button is-outlined m-r-10">
                <span class="icon">
                    <i class="fas fa-chevron-left"></i>
                </span>
              </a>Modifier</h1>
    </div>
    <!-- end of column -->

    <div class="column">
      <a href="{{route('permissions.edit', $permission->id)}}" class="button is-primary is-pulled-right"><i class="fa fa-edit m-r-10"></i> Edit Permission</a>
    </div>
  </div>
  <hr class="m-t-0">

  <form action="{{route('permissions.update', $permission->id)}}" method="POST">
    {{csrf_field()}} {{method_field('PUT')}}

    <div class="field">
      <label for="display_name" class="label">Name (Display Name)</label>
      <p class="control">
        <input type="text" class="input" name="display_name" id="display_name" value="{{$permission->display_name}}">
      </p>
    </div>

    <div class="field">
      <label for="name" class="label">Slug <small>(Cannot be changed)</small></label>
      <p class="control">
        <input type="text" class="input" name="name" id="name" value="{{$permission->name}}" disabled>
      </p>
    </div>

    <div class="field">
      <label for="description" class="label">Description</label>
      <p class="control">
        <input type="text" class="input" name="description" id="description" placeholder="Describe what this permission does" value="{{$permission->description}}">
      </p>
    </div>

    <button class="button is-primary">Save Changes</button>
  </form>
</div>
@endsection

resources/views/intranet/permissions/index.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')

<div class="columns">
  <div class="column">
    <h1 class="title">Permissions</h1>
  </div>
  <div class="column has-text-right">
    <a href="{{ route('permissions.create') }}" class="button is-primary has-text-white is-size-5"><i class="fas fa-plus"></i></a>
  </div>
</div>
<hr>

<div class="card">
  <div class="card-content">
    <table class="table is-hoverable is-fullwidth">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Slug</th>
          <th>Description</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        @foreach ($permissions as $permission)
        <tr>
          <td>{{$permission->display_name}}</td>
          <td>{{$permission->name}}</td>
          <td>{{$permission->description}}</td>
          <td class="has-text-right">
            <a href="{{route('permissions.show', $permission->id)}}" class="button is-outlined">
                <span class="icon">
                    <i class="far fa-eye"></i>
                  </span>
            </a>

            <a href="{{route('permissions.edit', $permission->id)}}" class="button is-outlined">
              <span class="icon">
                <i class="fas fa-pencil-alt"></i>
              </span>
              
            </a>
          </td>
        </tr>
        @endforeach
      </tbody>
    </table>
  </div>
</div>

{{-- {{$permissions->links('vendor.pagination.default')}} --}}
@endsection

resources/views/intranet/permissions/show.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')
<div class="flex-container">
  <div class="columns m-t-10">
    <div class="column">
      <h1 class="title">
        <a href="{{route('permissions.index')}}" class="button is-outlined m-r-10">
                <span class="icon">
                    <i class="fas fa-chevron-left"></i>
                </span>
              </a>Détails</h1>
    </div>
    <!-- end of column -->

    <div class="column">
      <a href="{{route('permissions.edit', $permission->id)}}" class="button is-primary is-pulled-right"><i class="fa fa-edit m-r-10"></i> Edit Permission</a>
    </div>
  </div>
  <hr class="m-t-0">

  <div class="columns">
    <div class="column">
      <div class="box">
        <article class="media">
          <div class="media-content">
            <div class="content">
              <p>
                <strong>{{$permission->display_name}}</strong> <small>{{$permission->name}}</small>
                <br> {{$permission->description}}
              </p>
            </div>
          </div>
        </article>
      </div>
    </div>
  </div>
</div>
@endsection