routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| MAIN
|--------------------------------------------------------------------------
*/

Route::get('/', 'Controller@home')->name('home');
Route::get('/club/presentation', 'Controller@presentation')->name('club.presentation');
Route::get('/club/equipe', 'Controller@equipe')->name('club.equipe');
Route::get('/horaires-tarifs/horaires', 'Controller@horaires')->name('horaires-tarifs.horaires');
Route::get('/horaires-tarifs/tarifs', 'Controller@tarifs')->name('horaires-tarifs.tarifs');
Route::get('/competitions/calendrier', 'Controller@calendrier')->name('competitions.calendrier');
Route::get('/competitions/resultats', 'Controller@resultats')->name('competitions.resultats');
Route::get('/galerie', 'Controller@galerie')->name('galerie');
Route::get('/galerie/{galerie}', 'Controller@galerieDetails')->name('galerieDetails');


/*
|--------------------------------------------------------------------------
| INTRANET
|--------------------------------------------------------------------------
*/

Auth::routes();

Route::prefix('intranet')->middleware('role:superadministrator|administrator|moderator|secretary|trainer|accountant|contributor|guest')->group(function(){
    Route::get('/', 'IntraController@index')->name('intranet');
    Route::get('dashboard', 'IntraController@dashboard')->name('intranet.dashboard');

    Route::get('/profil', 'ProfileController@showProfile')->name('showProfile');
    Route::get('/profil/edit','ProfileController@showChangePasswordForm')->name('editProfile');
    Route::post('/profil/edit','ProfileController@changePassword')->name('updateProfile');

    Route::get('/actualites/{actualite}/delete', 'ActualiteController@delete')->name('actualites.delete');

    Route::get('/judokas/{judoka}/unarchive', 'JudokaController@unarchive')->name('judokas.unarchive');
    Route::get('/judokas/{judoka}/pdf', 'JudokaController@pdf')->name('judokas.pdf');
    Route::resource('/judokas', 'JudokaController');

    Route::resource('/actualites', 'ActualiteController');
    Route::resource('/calendrier', 'CalendrierController');
    Route::resource('/resultats', 'ResultatController');
    Route::resource('/galerie', 'GalerieController');
    Route::resource('/fiches-de-frais', 'FraisController');

    Route::resource('/users', 'UserController');
    Route::resource('/permissions', 'PermissionController');
    Route::resource('/roles', 'RoleController');

    Route::get('/actualites/{actualite}/accept', 'ActualiteController@accept')->name('actualites.accept');
    Route::get('/actualites/{actualite}/reject', 'ActualiteController@reject')->name('actualites.reject');
    Route::get('/calendrier/{calendrier}/accept', 'CalendrierController@accept')->name('calendrier.accept');
    Route::get('/calendrier/{calendrier}/reject', 'CalendrierController@reject')->name('calendrier.reject');
});

resources/views/intranet/fiches-de-frais/create.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')

<div class="columns is-mobile">
  <div class="column">
    <h1 class="title">
      <a href="{{route('frais.index')}}" class="button is-outlined m-r-10">
        <span class="icon">
          <i class="fas fa-chevron-left"></i>
        </span>
      </a>Fiches de frais - create
    </h1>
  </div>
</div>
<hr>

<div class="card">
  <div class="card-content">
    ...
  </div>
</div>
@endsection
 
@section('scripts')
@endsection

resources/views/intranet/fiches-de-frais/edit.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')

<div class="columns is-mobile">
  <div class="column">
    <h1 class="title">
      <a href="{{route('frais.index')}}" class="button is-outlined m-r-10">
            <span class="icon">
                <i class="fas fa-chevron-left"></i>
            </span>
          </a>Fiches de frais - edit</h1>
  </div>
</div>
<hr>

<div class="card">
  <div class="card-content">
    ...
  </div>
</div>
@endsection
 
@section('scripts')
@endsection

resources/views/intranet/fiches-de-frais/index.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')

<div class="columns is-mobile">
  <div class="column">
    <h1 class="title">Fiches de frais</h1>
  </div>
  <div class="column has-text-right is-one-quarter">
    @if (Laratrust::can('create-frais'))
    <a href="{{ route('fiches-de-frais.create') }}" class="button is-primary has-text-white is-size-5"><i class="fas fa-plus"></i></a>@endif
  </div>
</div>
<hr>

<div class="card">
  <div class="card-content">
    ...
  </div>
</div>
@endsection
 
@section('scripts')
@endsection

resources/views/intranet/fiches-de-frais/show.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')

<div class="columns is-mobile">
  <div class="column">
    <h1 class="title">
      <a href="{{route('frais.index')}}" class="button is-outlined m-r-10">
        <span class="icon">
          <i class="fas fa-chevron-left"></i>
        </span>
      </a> Fiches de frais - show
    </h1>
  </div>
</div>
<hr>

<div class="card">
  <div class="card-content">
    ...
  </div>
</div>
@endsection
 
@section('scripts')
@endsection