routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| MAIN
|--------------------------------------------------------------------------
*/

Route::get('/', 'Controller@home')->name('home');
Route::get('/club/presentation', 'Controller@presentation')->name('club.presentation');
Route::get('/club/equipe', 'Controller@equipe')->name('club.equipe');
Route::get('/horaires-tarifs/horaires', 'Controller@horaires')->name('horaires-tarifs.horaires');
Route::get('/horaires-tarifs/tarifs', 'Controller@tarifs')->name('horaires-tarifs.tarifs');
Route::get('/competitions/calendrier', 'Controller@calendrier')->name('competitions.calendrier');
Route::get('/competitions/resultats', 'Controller@resultats')->name('competitions.resultats');
Route::get('/galerie', 'Controller@galerie')->name('galerie');
Route::get('/galerie/{galerie}', 'Controller@galerieDetails')->name('galerieDetails');


/*
|--------------------------------------------------------------------------
| INTRANET
|--------------------------------------------------------------------------
*/

Auth::routes();

Route::prefix('intranet')->middleware('role:superadministrator|administrator|moderator|secretary|trainer|accountant|contributor|guest')->group(function(){
    Route::get('/', 'IntraController@index')->name('intranet');
    Route::get('dashboard', 'IntraController@dashboard')->name('intranet.dashboard');

    Route::get('/profil', 'ProfileController@showProfile')->name('showProfile');
    Route::get('/profil/edit','ProfileController@showChangePasswordForm')->name('editProfile');
    Route::post('/profil/edit','ProfileController@changePassword')->name('updateProfile');

    Route::get('/actualites/{actualite}/delete', 'ActualiteController@delete')->name('actualites.delete');

    Route::get('/judokas/{judoka}/unarchive', 'JudokaController@unarchive')->name('judokas.unarchive');
    Route::get('/judokas/{judoka}/pdf', 'JudokaController@pdf')->name('judokas.pdf');
    Route::resource('/judokas', 'JudokaController');

    Route::resource('/actualites', 'ActualiteController');
    Route::resource('/calendrier', 'CalendrierController');
    Route::resource('/resultats', 'ResultatController');
    Route::resource('/galerie', 'GalerieController');
    Route::resource('/fiches-de-frais', 'FraisController');

    Route::resource('/users', 'UserController');
    Route::resource('/permissions', 'PermissionController');
    Route::resource('/roles', 'RoleController');

    Route::get('/actualites/{actualite}/accept', 'ActualiteController@accept')->name('actualites.accept');
    Route::get('/actualites/{actualite}/reject', 'ActualiteController@reject')->name('actualites.reject');
    Route::get('/calendrier/{calendrier}/accept', 'CalendrierController@accept')->name('calendrier.accept');
    Route::get('/calendrier/{calendrier}/reject', 'CalendrierController@reject')->name('calendrier.reject');
});

app/Role.php
<?php

namespace App;

use Laratrust\Models\LaratrustRole;

class Role extends LaratrustRole
{
    //
}

app/Http/Controllers/RoleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Role;
use App\Permission;
use Session;

class RoleController extends Controller
{
  public function __construct() {
    $this->middleware('role:superadministrator');
  }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $roles = Role::all();
      return view('intranet.roles.index')->withRoles($roles);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
      $permissions = Permission::all();
      return view('intranet.roles.create')->withPermissions($permissions);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
      $this->validateWith([
        'display_name' => 'required|max:255',
        'name' => 'required|max:100|alpha_dash|unique:roles',
        'description' => 'sometimes|max:255'
      ]);

      $role = new Role();
      $role->display_name = $request->display_name;
      $role->name = $request->name;
      $role->description = $request->description;
      $role->save();

      if ($request->permissions) {
        $role->syncPermissions(explode(',', $request->permissions));
      }

      return redirect()->route('roles.show', $role->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
      $role = Role::where('id', $id)->with('permissions')->first();
      return view('intranet.roles.show')->withRole($role);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
      $role = Role::where('id', $id)->with('permissions')->first();
      $permissions = Permission::all();
      return view('intranet.roles.edit')->withRole($role)->withPermissions($permissions);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validateWith([
        'display_name' => 'required|max:255',
        'description' => 'sometimes|max:255'
      ]);

      $role = Role::findOrFail($id);
      $role->display_name = $request->display_name;
      $role->description = $request->description;
      $role->save();

      if ($request->permissions) {
        $role->syncPermissions(explode(',', $request->permissions));
      }

      return redirect()->route('roles.show', $id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/intranet/roles/create.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')
<div class="flex-container">
  <div class="columns m-t-10">
    <div class="column">
      <h1 class="title">
        <a href="{{route('roles.index')}}" class="button is-outlined m-r-10">
          <span class="icon">
            <i class="fas fa-chevron-left"></i>
          </span>
        </a>Nouveau role
      </h1>
    </div>
  </div>
  <hr class="m-t-0">
  <form action="{{route('roles.store')}}" method="POST">
    {{ csrf_field() }}
    <div class="columns">
      <div class="column">
        <div class="box">
          <article class="media">
            <div class="media-content">
              <div class="content">
                <h2 class="title">Role Details:</h1>
                  <div class="field">
                    <p class="control">
                      <label for="display_name" class="label">Name (Human Readable)</label>
                      <input type="text" class="input" name="display_name" value="{{old('display_name')}}" id="display_name">
                    </p>
                  </div>
                  <div class="field">
                    <p class="control">
                      <label for="name" class="label">Slug (Can not be changed)</label>
                      <input type="text" class="input" name="name" value="{{old('name')}}" id="name">
                    </p>
                  </div>
                  <div class="field">
                    <p class="control">
                      <label for="description" class="label">Description</label>
                      <input type="text" class="input" value="{{old('description')}}" id="description" name="description">
                    </p>
                  </div>
                  <input type="hidden" :value="permissionsSelected" name="permissions">
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>

    <div class="columns">
      <div class="column">
        <div class="box">
          <article class="media">
            <div class="media-content">
              <div class="content">
                <h2 class="title">Permissions:</h1>
                  <b-checkbox-group>
                    @foreach ($permissions as $permission)
                    <div class="field">
                      <b-checkbox v-model="permissionsSelected" :native-value="{{$permission->id}}">{{$permission->display_name}} <em>({{$permission->description}})</em></b-checkbox>
                    </div>
                    @endforeach
              </div>
            </div>
          </article>
        </div>
        <!-- end of .box -->

        <button class="button is-primary">Create new Role</button>
      </div>
    </div>
  </form>
</div>
@endsection
 
@section('scripts')
<script>
  var app = new Vue({
    el: '#app',
    data: {
      permissionsSelected: []
    }
  });

</script>
@endsection

resources/views/intranet/roles/edit.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')
<div class="flex-container">
  <div class="columns m-t-10">
    <div class="column">
      <h1 class="title">
        <a href="{{route('roles.index')}}" class="button is-outlined m-r-10">
                <span class="icon">
                    <i class="fas fa-chevron-left"></i>
                </span>
              </a>Edit </h1>
    </div>
  </div>
  <hr class="m-t-0">
  <form action="{{route('roles.update', $role->id)}}" method="POST">
    {{ csrf_field() }} {{ method_field('PUT') }}
    <div class="columns">
      <div class="column">
        <div class="box">
          <article class="media">
            <div class="media-content">
              <div class="content">
                <h2 class="title">Role Details:</h1>
                  <div class="field">
                    <p class="control">
                      <label for="display_name" class="label">Name (Human Readable)</label>
                      <input type="text" class="input" name="display_name" value="{{$role->display_name}}" id="display_name">
                    </p>
                  </div>
                  <div class="field">
                    <p class="control">
                      <label for="name" class="label">Slug (Can not be edited)</label>
                      <input type="text" class="input" name="name" value="{{$role->name}}" disabled id="name">
                    </p>
                  </div>
                  <div class="field">
                    <p class="control">
                      <label for="description" class="label">Description</label>
                      <input type="text" class="input" value="{{$role->description}}" id="description" name="description">
                    </p>
                  </div>
                  <input type="hidden" :value="permissionsSelected" name="permissions">
              </div>
            </div>
          </article>
        </div>
      </div>
    </div>

    <div class="columns">
      <div class="column">
        <div class="box">
          <article class="media">
            <div class="media-content">
              <div class="content">
                <h2 class="title">Permissions:</h2>
                @foreach ($permissions as $permission)
                <div class="field">
                  <b-checkbox v-model="permissionsSelected" :native-value="{{$permission->id}}">{{$permission->display_name}} <em>({{$permission->description}})</em></b-checkbox>
                </div>
                @endforeach
              </div>
            </div>
          </article>
        </div>
        <!-- end of .box -->

        <button class="button is-primary">Save Changes to Role</button>
      </div>
    </div>
  </form>
</div>
@endsection
 
@section('scripts')
<script>
  var app = new Vue({
    el: '#app',
    data: {
      permissionsSelected: {!!$role->permissions->pluck('id')!!}
    }
  });

</script>
@endsection

resources/views/intranet/roles/index.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')

<div class="columns">
    <div class="column">
        <h1 class="title">Roles</h1>
    </div>
    <div class="column has-text-right">
        <a href="{{ route('roles.create') }}" class="button is-primary has-text-white is-size-5"><i class="fas fa-plus"></i></a>
    </div>
</div>
<hr>

<div class="columns is-multiline">
    @foreach ($roles as $role)
    <div class="column is-one-quarter">
        <div class="box">
            <article class="media">
                <div class="media-content has-text-centered">

                    <p class="is-size-5"><b>{{$role->display_name}}</b></p>
                    <p>{{$role->description}}</p>

                    <hr>
                    <div>
                        <a href="{{route('roles.show', $role->id)}}" class="button is-outlined">
                            <span class="icon">
                            <i class="far fa-eye"></i>
                            </span>
                        </a>
                        <a href="{{route('roles.edit', $role->id)}}" class="button is-outlined is-hidden-mobile">
                            <span class="icon">
                            <i class="fas fa-pencil-alt"></i>
                            </span>
                        </a>
                    </div>

                </div>
            </article>
        </div>
    </div>
    @endforeach
</div>
@endsection

resources/views/intranet/roles/show.blade.php
@extends('layouts.layouts-intranet.master') 
@section('content')

<div class="columns">
    <div class="column">
        <h1 class="title">
            <a href="{{route('roles.index')}}" class="button is-outlined m-r-10">
                <span class="icon">
                    <i class="fas fa-chevron-left"></i>
                </span>
            </a> Détails
            </small>
        </h1>
    </div>
    <div class="column has-text-right">
        <a href="{{ route('roles.edit', $role->id) }}" class="button is-primary has-text-white is-size-5"><i class="fas fa-pen-alt"></i>Modifier</a>
    </div>
</div>
<hr>

<div class="columns">
    <div class="column">
        <div class="box">
            <article class="media">
                <div class="media-content">
                    <div class="content">
                        <h2 class="title">Permissions:</h1>
                            <ul>
                                @foreach ($role->permissions as $r)
                                <li>{{$r->display_name}} <em class="m-l-15">({{$r->description}})</em></li>
                                @endforeach
                            </ul>
                    </div>
                </div>
            </article>
        </div>
    </div>
</div>
@endsection